
const Faq = () => {
  return (
    <section className="py-16 bg-white lg:py-24">
        <div className="max-w-6xl mx-auto px-4">
            <div className="text-center">
                <h2 className="font-semibold text-3xl lg:text-4xl mb-2">Frequently asked questions</h2>
                <p className="text-slate-600 text-sm md:text-base">Everything you need to know about FlowAI.</p>
            </div>

            <div className="flex flex-col gap-4 mt-4 max-w-3xl mx-auto">
                <div className="border border-slate-500 rounded-xl overflow-hidden px-4 py-2">
                    <h4 className="font-semibold mb-2 text-lg md:text-xl">Is there a free plan available?</h4>
                    <p className="text-slate-600 text-sm">Yes. You can start using FlowAI with our free plan and upgrade anytime when you need more features.</p>
                </div>

                 <div className="border border-slate-500 rounded-xl overflow-hidden px-4 py-2">
                    <h4 className="font-semibold mb-2 text-lg md:text-xl">What type of content can FlowAI generate?</h4>
                    <p className="text-slate-600 text-sm">FlowAI can generate blog posts, social media captions, ad copy, emails, product descriptions, and much more.</p>
                </div>

                 <div className="border border-slate-500 rounded-xl overflow-hidden px-4 py-2">
                    <h4 className="font-semibold mb-2 text-lg md:text-xl">Is the content generated by AI unique?</h4>
                    <p className="text-slate-600 text-sm">Yes. FlowAI uses advanced AI models to generate original content based on your input and context.</p>
                </div>

                 <div className="border border-slate-500 rounded-xl overflow-hidden px-4 py-2">
                    <h4 className="font-semibold mb-2 text-lg md:text-xl">Can I collaborate with my team?</h4>
                    <p className="text-slate-600 text-sm">Absolutely. Our Pro and Business plans allow team members to collaborate and manage content together.</p>
                </div>

                <div className="border border-slate-500 rounded-xl overflow-hidden px-4 py-2">
                    <h4 className="font-semibold mb-2 text-lg md:text-xl">Can I cancel my subscription anytime?</h4>
                    <p className="text-slate-600 text-sm">Yes. You can cancel your subscription anytime directly from your dashboard.</p>
                </div>
            </div>
        </div>
    </section>
  )
}

export default Faq